"""add_phone_number_to_user

Revision ID: 387de0f112e8
Revises: fb22a1a862ec
Create Date: 2022-08-12 14:41:17.845318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387de0f112e8'
down_revision = 'fb22a1a862ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
