name: Build and Deploy Code

on: [push, pull_request]

# push, for multiple, [push, pull_request] on every branch, but what if you want specific branches?
#   push: # define branches
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# create a job, a set of steps that execute on the same runner 
jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Postgres_098
      DATABASE_NAME: fastapi_db
      DATABASE_USERNAME: postgres
      SECRET_KEY: 52595a0a200c17539624b8dc5b8207226e99105498143a67194b4a5b3c02831a
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.10"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run pytest tests # | does list of commands
        run: |
          pip install pytest
          pytest
# will fail at the moment, no Environment Vars
